// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Verifies and corrects check data by comparing numerical and written amounts,
 * detecting inconsistencies, and suggesting corrections.
 *
 * - verifyAndCorrectCheckData - A function that handles the check data verification and correction process.
 * - VerifyAndCorrectCheckDataInput - The input type for the verifyAndCorrectCheckData function.
 * - VerifyAndCorrectCheckDataOutput - The return type for the verifyAndCorrectCheckData function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const VerifyAndCorrectCheckDataInputSchema = z.object({
  amountInNumbers: z.string().describe('The amount in numbers extracted from the check.'),
  amountInWords: z.string().describe('The amount in words extracted from the check.'),
  checkDate: z.string().describe('The date on the check.'),
  payee: z.string().describe('The payee on the check.'),
});

export type VerifyAndCorrectCheckDataInput = z.infer<typeof VerifyAndCorrectCheckDataInputSchema>;

const VerifyAndCorrectCheckDataOutputSchema = z.object({
  isConsistent: z.boolean().describe('Whether the amount in numbers and words are consistent.'),
  correctedAmountInNumbers: z.string().optional().describe('The corrected amount in numbers, if any.'),
  correctedAmountInWords: z.string().optional().describe('The corrected amount in words, if any.'),
  flaggedIssues: z.array(z.string()).describe('Any issues that were automatically flagged with the check data.'),
});

export type VerifyAndCorrectCheckDataOutput = z.infer<typeof VerifyAndCorrectCheckDataOutputSchema>;

export async function verifyAndCorrectCheckData(input: VerifyAndCorrectCheckDataInput): Promise<VerifyAndCorrectCheckDataOutput> {
  return verifyAndCorrectCheckDataFlow(input);
}

const verifyAndCorrectCheckDataPrompt = ai.definePrompt({
  name: 'verifyAndCorrectCheckDataPrompt',
  input: {
    schema: z.object({
      amountInNumbers: z.string().describe('The amount in numbers extracted from the check.'),
      amountInWords: z.string().describe('The amount in words extracted from the check.'),
      checkDate: z.string().describe('The date on the check.'),
      payee: z.string().describe('The payee on the check.'),
    }),
  },
  output: {
    schema: z.object({
      isConsistent: z.boolean().describe('Whether the amount in numbers and words are consistent.'),
      correctedAmountInNumbers: z.string().optional().describe('The corrected amount in numbers, if any.'),
      correctedAmountInWords: z.string().optional().describe('The corrected amount in words, if any.'),
      flaggedIssues: z.array(z.string()).describe('Any issues that were automatically flagged with the check data.'),
    }),
  },
  prompt: `You are an expert AI assistant for verifying and correcting check data.

You will be given the amount in numbers, amount in words, check date, and payee extracted from a check.

Your task is to determine if the amount in numbers and amount in words are consistent. If they are not, provide corrected versions of both amounts, if possible. Also, flag any other potential issues with the check data.

Amount in Numbers: {{{amountInNumbers}}}
Amount in Words: {{{amountInWords}}}
Check Date: {{{checkDate}}}
Payee: {{{payee}}}

Consider if the extracted data is valid. For example, is the date a valid date?

Output whether the data is consistent, corrections for the amount in numbers and words (if needed), and any other flagged issues.
`,
});

const verifyAndCorrectCheckDataFlow = ai.defineFlow<
  typeof VerifyAndCorrectCheckDataInputSchema,
  typeof VerifyAndCorrectCheckDataOutputSchema
>({
  name: 'verifyAndCorrectCheckDataFlow',
  inputSchema: VerifyAndCorrectCheckDataInputSchema,
  outputSchema: VerifyAndCorrectCheckDataOutputSchema,
}, async input => {
  const {output} = await verifyAndCorrectCheckDataPrompt(input);
  return output!;
});
